import localFont from "next/font/local"
import Link from "next/link"
import "./globals.css"
import LoginBtn from "./loginBtn"
import LogoutBtn from "./logoutBtn"
import { getServerSession } from "next-auth"
import { authOptions } from "@/pages/api/auth/[...nextauth]"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
          <h1 className="title">오늘의 먹거리</h1>
          <Link href="/list">Home</Link>
          <Link href="/my_fridge">나만의 냉장고</Link>
          <Link href="/food_roulette">음식 추천 룰렛</Link>
          <Link href="/write">글쓰기</Link>
          {
            session ? <span className="sign">{session.user.name}<LogoutBtn/></span>: <span className="sign"><LoginBtn></LoginBtn></span>
          }
        </div>
        {children}
      </body>
    </html>
  );
}
